# -*- coding: utf-8 -*-
"""EngRemover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTdwPy2oPQa3AgryAZjfx3FGx1XnkR12
"""

import re

def word_overlap_ratio(line1, line2):                                                   #computes ratio between lines
    w1 = set(re.findall(r"[A-Za-z']+", line1.lower()))
    w2 = set(re.findall(r"[A-Za-z']+", line2.lower()))
    if not w1 or not w2:
        return 0.0
    overlap = len(w1 & w2)
    total = min(len(w1), len(w2))
    return overlap / total if total > 0 else 0.0

def clean_parallel(en_file, tl_file, out_en, out_tl, threshold=0.7):             #cleans out matching lines
    removed = 0
    kept = 0
    lines_removed = []

    with open(en_file, 'r', encoding='utf-8') as f_en, \
         open(tl_file, 'r', encoding='utf-8') as f_tl, \
         open(out_en, 'w', encoding='utf-8') as out_en_f, \
         open(out_tl, 'w', encoding='utf-8') as out_tl_f:

        for line_num, (en_line, tl_line) in enumerate(zip(f_en, f_tl), start=1):
            en_line, tl_line = en_line.strip(), tl_line.strip()


            if not en_line or not tl_line:                                             # Skip empty lines or lines that are too similar
                continue

            overlap = word_overlap_ratio(en_line, tl_line)

            if overlap > threshold:
                removed += 1
                if len(lines_removed) < 10:                             # only keep first 10 removed lines
                  lines_removed.append((line_num, tl_line))
                continue

            out_en_f.write(en_line + "\n")
            out_tl_f.write(tl_line + "\n")
            kept += 1

    print(f"Clean complete")
    print(f"Kept: {kept} pairs")
    print(f"Removed: {removed} pairs (over {threshold*100:.0f}% word overlap)")
    print(f"Saved to:\n  - {out_en}\n  - {out_tl}")

    if lines_removed:
        print("\nFirst 10 lines removed (with original line numbers):")
        for i, (line_num, line) in enumerate(lines_removed, 1):
            print(f"{i}. Line {line_num}: {line}")


clean_parallel(
    en_file='OpenSubtitles.en-tl.en',
    tl_file='OpenSubtitles.en-tl.tl',
    out_en='clean.en-tl.en',
    out_tl='clean.en-tl.tl',
    threshold=0.7  # Remove if >70% of words are shared
)